### ISSUE TITLE
Jigsaw problem

### ISSUE THREAD

**Issue by PortableGames** [LordDeatHunter/FabricWaystones#102]
Minecraft 1.18.2 fabric polymer port

Hi I have a problem with waystones not generating at all in villages and every time I visit a new village the console lists many errors

Like:
Thread.java:833) [?:?]
[14:35:26] [Server thread/ERROR]: Input does not contain a key [element_type]: MapLike[{}]
[14:35:26] [Server thread/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
at net.minecraft.class_3790.method_35448(class_3790.java:54) ~[server-intermediary.jar:?]
at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]

**Comment by LordDeatHunter** [comment]
Fixed on my side, I'm not sure how Polymer syncs with the main mod.
