### ISSUE TITLE
FabricWaystones crashes Minecraft

### ISSUE THREAD

**Issue by Lolothepro** [LordDeatHunter/FabricWaystones#110]
![image](https://user-images.githubusercontent.com/68275908/165345821-082281ae-09d6-4268-815a-e79d2ab87899.png)

```
Exception stopping the server
	at wraith.waystones.util.WaystonesEventManager.lambda$registerEvents$1(WaystonesEventManager.java:29) ~[wraith-waystones-2.5.0.jar:?]
	at wraith.waystones.util.WaystonesEventManager.lambda$registerEvents$1(WaystonesEventManager.java:29) ~[wraith-waystones-2.5.0.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$6(ServerLifecycleEvents.java:75) ~[fabric-lifecycle-events-v1-2.0.3+2d83e92c60-9b014c802997cc2d.jar:?]
	at net.minecraft.server.MinecraftServer.handler$cde000$afterShutdownServer(MinecraftServer:5322) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.shutdown(MinecraftServer:643) ~[client-intermediary.jar:?]
	at net.minecraft.server.integrated.IntegratedServer.shutdown(IntegratedServer:193) ~[?:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:729) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by LordDeatHunter** [comment]
That's not the full crash log. Something else is crashing the server, which prevents FWaystones from saving data successfully. Send the full log just in case.

**Comment by Lolothepro** [comment]
[latest.log](https://github.com/LordDeatHunter/FabricWaystones/files/8565573/latest.log)

**Comment by LordDeatHunter** [comment]
Were you playing on singleplayer with LAN open?

**Comment by Lolothepro** [comment]
singleplayer without LAN open
