### ISSUE TITLE
[Bug]: Errors on loading villages containing waystones

### ISSUE THREAD

**Issue by CammB** [LordDeatHunter/FabricWaystones#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There is another issue of this type however it is not open and not been assigned anyone. When loading into villages i get on of two errors mainly. One where players are trying to access and inventory before it was created and one relating to the jigsaw block. i also have repurposed structures installed so maybe something to do with that.

Waystones do seem to be spawning, if anything too frequently so ive reduced the village spawn weight down to 1.

### To Reproduce

1. start a fresh generated world with said mods installed
2. locate a village an tp or tavel to
3. as village loads in errors thrown in cosole

### Expected behavior

waystone to load in without errors or unneccesary load on the server reducing lag and preventing crashes from using waystones occasionally.

### Mod Version

v2.5.0

### Minecraft Version

1.18.2

### Java Version

Java 17

### Fabric Version

- **Fabric:** ex. 0.13.3-1-18-2
- **Fabric API:** ex. 0.51.1+1.18.2

### Relevant log output

```shell
[09:39:54] [Server thread/INFO]: [DankBrockoli: Teleported DankBrockoli to -3983.500000, 91.350335, -415.500000]
[09:39:56] [Worker-Main-151/WARN]: Tried to access a block entity before it was created. class_2338{x=-3997, y=65, z=-412}
[09:39:56] [Worker-Main-151/WARN]: Tried to access a block entity before it was created. class_2338{x=-3997, y=65, z=-412}
[09:39:57] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2668ms or 53 ticks behind
[09:39:59] [Server thread/WARN]: Tried to load a block entity for block Block{waystones:waystone}[active=false,facing=west,half=upper,mossy=false,waterlogged=false] but failed at location class_2338{x=-3997, y=65, z=-412}

[09:46:03] [Server thread/ERROR]: Input does not contain a key [element_type]: MapLike[{}]
[09:46:03] [Server thread/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
	at net.minecraft.class_3790.method_35448(class_3790.java:54) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_3790.<init>(class_3790.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_6624.method_38711(class_6624.java:73) ~[server-intermediary.jar:?]
	at net.minecraft.class_3195.method_28660(class_3195.java:129) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.method_12392(class_2852.java:468) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.method_12395(class_2852.java:199) ~[server-intermediary.jar:?]
	at net.minecraft.class_3898.method_17256(class_3898.java:605) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:552) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:561) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:278) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:796) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:768) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[09:46:03] [Server thread/ERROR]: Input does not contain a key [element_type]: MapLike[{}]
[09:46:03] [Server thread/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
	at net.minecraft.class_3790.method_35448(class_3790.java:54) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_3790.<init>(class_3790.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_6624.method_38711(class_6624.java:73) ~[server-intermediary.jar:?]
	at net.minecraft.class_3195.method_28660(class_3195.java:129) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.method_12392(class_2852.java:468) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.method_12395(class_2852.java:199) ~[server-intermediary.jar:?]
	at net.minecraft.class_3898.method_17256(class_3898.java:605) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:552) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:561) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:278) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:796) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:768) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Anything else?

![screenshot](https://user-images.githubusercontent.com/63784592/168263505-dcf5d30e-3204-45c3-85f3-ee4836a1667d.png)

**Comment by LordDeatHunter** [comment]
Looks similar to some of the other village-gen issues, should be fixed.
