### ISSUE TITLE
[Bug]: Void Totem disconnects you when activating

### ISSUE THREAD

**Issue by Dawnbreak-z** [LordDeatHunter/FabricWaystones#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After void totem activates, the game blackscreens (loading screen), then after a few seconds connection lost. Displaying the message "Internal Exception: net.minecraft.class_148: Exception while adding particle."

### To Reproduce

1. Have BetterMC 1.19.2v16.5 installed
2. Place a Waystone and bound Void Totem to Waystone
3. Have Void Totem in inventory
4. Kill self (lava, fall damage, and void produce the same result)
5. Black loading screen
6. Connection lost

### Expected behavior

Void Totem revives and teleports you to the bounded Waystone.

### Mod Version

v3.0.7 or newer

### Minecraft Version

1.19.2

### Java Version

Other

### Fabric Version

- **Fabric:** 0.14.17
- **Fabric API:** 0.75.1+1.19.2

### Relevant log output

```shell
[24/03/2023 19:36:20 PM] 	at com.ishland.uwrad.common.CheckedThreadLocalRandom.handleNotOwner(CheckedThreadLocalRandom.java:51)
[24/03/2023 19:36:20 PM] 	at com.ishland.uwrad.common.CheckedThreadLocalRandom.isSafe(CheckedThreadLocalRandom.java:38)
[24/03/2023 19:36:20 PM] 	at com.ishland.uwrad.common.CheckedThreadLocalRandom.method_43156(CheckedThreadLocalRandom.java:82)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_6566.method_43048(class_6566.java:33)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_761.method_3268(net/minecraft/class_761.java:2790)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_761.method_3288(net/minecraft/class_761.java:2760)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_761.method_8563(net/minecraft/class_761.java:2731)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_761.method_8568(net/minecraft/class_761.java:2726)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_638.method_8466(net/minecraft/class_638.java:612)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_733.method_3070(class_733.java:42)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_733.<init>(class_733.java:27)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_733.<init>(class_733.java:19)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_702.method_3051(net/minecraft/class_702.java:290)
[24/03/2023 19:36:20 PM] 	at wraith.fwaystones.client.WaystonesClient.lambda$registerPacketHandlers$4(WaystonesClient.java:73)
[24/03/2023 19:36:20 PM] 	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:106)
[24/03/2023 19:36:20 PM] 	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:42)
[24/03/2023 19:36:20 PM] 	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101)
[24/03/2023 19:36:20 PM] 	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:98)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_634.handler$eaa000$fabric-networking-api-v1$handleCustomPayload(net/fabricmc/fabric/mixin/networking/client/ClientPlayNetworkHandlerMixin.java [fabric-networking-api-v1.client.mixins.json]:65)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_634.method_11152(class_634.java)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_2658.method_11457(net/minecraft/class_2658.java:60)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_2658.method_11054(net/minecraft/class_2658.java:8)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_2535.method_10759(net/minecraft/class_2535.java:167)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_2535.method_10770(net/minecraft/class_2535.java:152)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_2535.channelRead0(net/minecraft/class_2535.java:50)
[24/03/2023 19:36:20 PM] 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[24/03/2023 19:36:20 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[24/03/2023 19:36:20 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[24/03/2023 19:36:20 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[24/03/2023 19:36:20 PM] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[24/03/2023 19:36:20 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[24/03/2023 19:36:20 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[24/03/2023 19:36:20 PM] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[24/03/2023 19:36:20 PM] 	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
[24/03/2023 19:36:20 PM] 	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
[24/03/2023 19:36:20 PM] 	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
[24/03/2023 19:36:20 PM] 	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
[24/03/2023 19:36:20 PM] 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[24/03/2023 19:36:20 PM] 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[24/03/2023 19:36:20 PM] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[24/03/2023 19:36:20 PM] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[24/03/2023 19:36:20 PM] 	at java.base/java.lang.Thread.run(Thread.java:833)
[24/03/2023 19:36:20 PM] [Netty Local Client IO #1/ERROR] ThreadLocalRandom accessed from a different thread (owner: Render thread, current: Netty Local Client IO #1)
[24/03/2023 19:36:20 PM] [Netty Local Client IO #1/INFO] [STDOUT]: Negative index in crash report handler (0/36)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_761.method_8563(class_761.java:2740)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_761.method_8568(class_761.java:2726)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_638.method_8466(class_638.java:612)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_733.method_3070(class_733.java:42)
[24/03/2023 19:36:20 PM] 	at net.minecraft.class_733.<init>(class_733.java:27)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_733.<init>(class_733.java:19)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_702.method_3051(class_702.java:290)
[24/03/2023 19:36:21 PM] 	at wraith.fwaystones.client.WaystonesClient.lambda$registerPacketHandlers$4(WaystonesClient.java:73)
[24/03/2023 19:36:21 PM] 	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:106)
[24/03/2023 19:36:21 PM] 	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:42)
[24/03/2023 19:36:21 PM] 	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101)
[24/03/2023 19:36:21 PM] 	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:98)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_634.handler$eaa000$fabric-networking-api-v1$handleCustomPayload(class_634.java:2522)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_634.method_11152(class_634.java)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_2658.method_11457(class_2658.java:60)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_2658.method_11054(class_2658.java:8)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_2535.method_10759(class_2535.java:167)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_2535.method_10770(class_2535.java:152)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_2535.channelRead0(class_2535.java:50)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
[24/03/2023 19:36:21 PM] 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[24/03/2023 19:36:21 PM] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[24/03/2023 19:36:21 PM] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[24/03/2023 19:36:21 PM] 	at java.base/java.lang.Thread.run(Thread.java:833)
[24/03/2023 19:36:21 PM] Caused by: com.ishland.uwrad.common.CheckedThreadLocalRandom$1: ThreadLocalRandom accessed from a different thread (owner: Render thread, current: Netty Local Client IO #1)
[24/03/2023 19:36:21 PM] Possible solutions: Find possible causes in the stack trace below and report to the corresponding mod authors 
[24/03/2023 19:36:21 PM]  
[24/03/2023 19:36:21 PM]  (You may make this a fatal warning instead of a hard crash with enforce_safe_world_random_access setting in uwrad.properties)
[24/03/2023 19:36:21 PM] Caused by: java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Render thread, current: Netty Local Client IO #1)
[24/03/2023 19:36:21 PM] 	at com.ishland.uwrad.common.CheckedThreadLocalRandom.handleNotOwner(CheckedThreadLocalRandom.java:51)
[24/03/2023 19:36:21 PM] 	at com.ishland.uwrad.common.CheckedThreadLocalRandom.isSafe(CheckedThreadLocalRandom.java:38)
[24/03/2023 19:36:21 PM] 	at com.ishland.uwrad.common.CheckedThreadLocalRandom.method_43156(CheckedThreadLocalRandom.java:82)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_6566.method_43048(class_6566.java:33)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_761.method_3268(net/minecraft/class_761.java:2790)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_761.method_3288(net/minecraft/class_761.java:2760)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_761.method_8563(net/minecraft/class_761.java:2731)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_761.method_8568(net/minecraft/class_761.java:2726)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_638.method_8466(net/minecraft/class_638.java:612)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_733.method_3070(class_733.java:42)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_733.<init>(class_733.java:27)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_733.<init>(class_733.java:19)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_702.method_3051(net/minecraft/class_702.java:290)
[24/03/2023 19:36:21 PM] 	at wraith.fwaystones.client.WaystonesClient.lambda$registerPacketHandlers$4(WaystonesClient.java:73)
[24/03/2023 19:36:21 PM] 	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:106)
[24/03/2023 19:36:21 PM] 	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:42)
[24/03/2023 19:36:21 PM] 	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101)
[24/03/2023 19:36:21 PM] 	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:98)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_634.handler$eaa000$fabric-networking-api-v1$handleCustomPayload(net/fabricmc/fabric/mixin/networking/client/ClientPlayNetworkHandlerMixin.java [fabric-networking-api-v1.client.mixins.json]:65)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_634.method_11152(class_634.java)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_2658.method_11457(net/minecraft/class_2658.java:60)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_2658.method_11054(net/minecraft/class_2658.java:8)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_2535.method_10759(net/minecraft/class_2535.java:167)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_2535.method_10770(net/minecraft/class_2535.java:152)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_2535.channelRead0(net/minecraft/class_2535.java:50)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
[24/03/2023 19:36:21 PM] 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[24/03/2023 19:36:21 PM] 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[24/03/2023 19:36:21 PM] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[24/03/2023 19:36:21 PM] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[24/03/2023 19:36:21 PM] 	at java.base/java.lang.Thread.run(Thread.java:833)
[24/03/2023 19:36:21 PM] [Netty Local Client IO #1/ERROR] Encountered exception while handling in channel with name "fwaystones:void_totem_revive"
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_761.method_8563(class_761.java:2740)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_761.method_8568(class_761.java:2726)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_638.method_8466(class_638.java:612)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_733.method_3070(class_733.java:42)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_733.<init>(class_733.java:27)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_733.<init>(class_733.java:19)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_702.method_3051(class_702.java:290)
[24/03/2023 19:36:21 PM] 	at wraith.fwaystones.client.WaystonesClient.lambda$registerPacketHandlers$4(WaystonesClient.java:73)
[24/03/2023 19:36:21 PM] 	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:106)
[24/03/2023 19:36:21 PM] 	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:42)
[24/03/2023 19:36:21 PM] 	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101)
[24/03/2023 19:36:21 PM] 	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:98)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_634.handler$eaa000$fabric-networking-api-v1$handleCustomPayload(class_634.java:2522)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_634.method_11152(class_634.java)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_2658.method_11457(class_2658.java:60)
[24/03/2023 19:36:21 PM] 	at net.minecraft.class_2658.method_11054(class_2658.java:8)
```

### Anything else?

Java version is Java 8 Update 361

**Comment by allanonmage** [comment]
I have seen 2 different kinds of void totems, one from Enderscape, and one from Goblin Traders.  Which mod did you get your void totem from?  I'm not the creator, but that's on my list of things to fix on my server.

**Comment by Dawnbreak-z** [comment]
The void totem is from this mod
