### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by invizbleRope** [LordDeatHunter/FabricWaystones#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -1 is negative
	at java.base/java.lang.System.arraycopy(Native Method)
	at java.base/java.io.PushbackInputStream.unread(PushbackInputStream.java:232)
	at net.minecraft.class_26.method_17921(class_26.java:114)
	at net.minecraft.class_26.method_17923(class_26.java:90)
	at wraith.fwaystones.util.WaystoneStorage.loadOrSaveWaystones(WaystoneStorage.java:159)
	at wraith.fwaystones.util.WaystoneStorage.<init>(WaystoneStorage.java:62)
	at wraith.fwaystones.util.WaystonesEventManager.lambda$registerEvents$0(WaystonesEventManager.java:22)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
	at net.minecraft.server.MinecraftServer.handler$bbp000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:2842)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

### To Reproduce

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 4.15.0-163-generic
	Java Version: 17.0.7, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 1296203048 bytes (1236 MiB) / 2747269120 bytes (2620 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E3-1270 v5 @ 3.60GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: 100 Series/C230 Series Chipset Family Integrated Sensor Hub
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0xa135
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: ASPEED Graphics Family
	Graphics card #1 vendor: ASPEED Technology, Inc. (0x1a03)
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: 0x2000
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MB): 97484.08
	Virtual memory used (MB): 52942.34
	Swap memory total (MB): 65360.00
	Swap memory used (MB): 35.50
	JVM Flags: 3 total; -Xmx3072M -Xms256M -XX:ParallelGCThreads=2
	Fabric Mods: 
		adorn: Adorn 5.0.0+1.20.1
		architectury: Architectury 9.0.8
		bclib: BCLib 3.0.10
			wunderlib: WunderLib 1.1.3
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0
		betterend: Better End 4.0.7
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0
		betternether: Better Nether 9.0.7
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0
		bettervillage: Better village 3.1.0
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0
		chunky: Chunky 1.3.92
		collective: Collective 6.62
		dungeons_arise: When Dungeons Arise 2.1.56
		elytratrims: Elytra Trims 1.1.9
			conditional-mixin: conditional mixin 0.3.2
		fabric-api: Fabric API 0.83.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a77
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.11+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b77
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b77
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b77
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabric-language-kotlin: Fabric Language Kotlin 1.9.6+kotlin.1.8.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		ferritecore: FerriteCore 6.0.0
		friendsandfoes: Friends&Foes 1.9.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		fscript: FScript Lib 3.2.1
		fwaystones: Fabric Waystones 3.1.2+mc1.20
		jade: Jade 11.1.4
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.2.0.22
		journeymap: Journeymap 5.9.10
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		libraryferret: Library ferret 4.0.0
		lithium: Lithium 0.11.2
		lootr: Lootr 0.7.29.71
		minecraft: Minecraft 1.20.1
		moonlight: Moonlight 1.20-2.5.14
		origins: Origins 1.10.0
			apoli: Apoli 2.9.0
				additionalentityattributes: Additional Entity Attributes 1.3.0+1.20.0
				calio: Calio 1.11.0
				cardinal-components-base: Cardinal Components API (base) 5.2.1
				cardinal-components-entity: Cardinal Components API (entities) 5.2.1
				playerabilitylib: Pal 1.8.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		origins-minus: Origins Minus 2.0.6+1.19.3
		owo: oωo 0.11.0+1.20
			blue_endless_jankson: jankson 1.2.2
		pack_it_up: Pack It Up! 0.3.1+1.20.1
		pehkui: Pehkui 3.7.6+1.14.4-1.20.1
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		servux: Servux 0.1.0
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
			cloth-config: Cloth Config v11 11.0.99
				cloth-basic-math: cloth-basic-math 0.6.1
		supplementaries: Supplementaries 1.20-2.5.11
		survivalflight: Survival Flight 1.3.3
			tf_ssf_sfort_ini_sf-ini: SF-INI 1
		traverse: Traverse 7.0.7
			biolith: Biolith 1.0.0-alpha.7
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 7.0.1
			terraform-config-api-v1: Terraform Config API (v1) 7.0.1
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 7.0.1
			terraform-tree-api-v1: Terraform Tree API (v1) 7.0.1
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
			traverse-common: Traverse: Common 7.0.7
			traverse-worldgen: Traverse: World Generation 7.0.7
		treeharvester: Tree Harvester 8.1
		trimmable_tools: Trimmable Tools 1.0.4
		viewdistancefix: View Distance Fix 1.20.1-1.0.0
		villagernames: Villager Names 5.2
		voicechat: Simple Voice Chat 1.20.1-2.4.12
		yungsapi: YUNG's API 1.20-Fabric-4.0-beta0
			org_javassist_javassist: javassist 3.29.2-GA
		yungsbridges: YUNG's Bridges 1.20-Fabric-4.0
		yungsextras: YUNG's Extras 1.20-Fabric-4.0
	Server Running: true
	Player Count: 0 / 5; []
	Data Packs: vanilla, fabric, file/anti enderman grief v1.1.4 (MC 1.20.x).zip, file/armor statues v2.8.5 (MC 1.20.x).zip, file/armored elytra v1.0.7 (MC 1.20.x).zip, file/confetti creepers v2.2.4 (MC 1.20.x).zip, file/coordinates hud v1.2.4 (MC 1.20.x).zip, file/double shulker shells v1.3.4 (MC 1.20.x).zip, file/dp-trimmable-tools-mc1, file/durability ping v1.1.4 (MC 1.20.x).zip, file/graves v2.8.8 (MC 1.20.x).zip, file/magical_items-1.7, file/more mob heads v2.12.1 (MC 1.20.x).zip, file/name colors v1.0.2 (MC 1.20.x).zip, file/nether portal coords v1.1.4 (MC 1.20.x).zip, file/player head drops v1.1.4 (MC 1.20.x).zip, file/real time clock v1.1.4 (MC 1.20.x).zip, file/redstone rotation wrench v1.1.5 (MC 1.20.x).zip, file/silence mobs v1.1.4 (MC 1.20.x).zip, file/spectator conduit power v1.1.4 (MC 1.20.x).zip, file/spectator night vision v1.1.4 (MC 1.20.x).zip, file/terracotta rotation wrench v1.1.5 (MC 1.20.x).zip, file/unlock all recipes v2.0.5 (MC 1.20.x).zip, file/villager workstation highlights v1.1.4 (MC 1.20.x).zip, file/wandering trades v1.7.1 (MC 1.20.x).zip, Supplementaries Generated Pack
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

### Expected behavior

I expect Minecraft won't crash

### Mod Version

v3.1.1 or newer

### Minecraft Version

1.20 or newer

### Java Version

Java 17

### Fabric Version

- **Fabric:** ex. 0.14.21-1.20.1
- **Fabric API:** ex. 0.85.0+1.20.1

### Anything else?

It crashed 14 times at list in the spend of less then 2 hours and the cause of all the crashes is the same "array out of bound exception" with the -1 as the length as show above.  No one was playing on the server during this time.  The last two crash reports are 0 byte in size due to no more space on the server.  The reason for running of space on the server is still unknown but we think that is related to the crashes.

**Comment by invizbleRope** [comment]
The issue is gone after we uninstalled all the mods and reinstalled them with my backup world.  Since we didn't play and couldn't play at all after the backup world was created (midnight my time), we don't think it was the world.  We still don't know what caused the problem but are glad that we can play again!

Any thank you for your help
