### ISSUE TITLE
[Bug]: Error loading saved data: fw_waystones

### ISSUE THREAD

**Issue by invizbleRope** [LordDeatHunter/FabricWaystones#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Waystones mod cause the server to crash after trimming the world.  This happen even after the waystones mod was deleted from the server, restarted the world for it to regenerate all the missing blocks where the Waystones were, and then reintalled the Waystones.  Once the Waystones mod was reinstalled, the server would not start.  The error messages before removing Waystones and after reinstalling it back on the log are identical. 

All proper steps were followed when removing and reinstalling the Waystones mod, i.e. stop the server before the actions and start the server afterwards.

### To Reproduce

1. Install fw_waystone
2. server crash during startup
3. uninstall fw_waystone
4. server start normal

### Expected behavior

The Minecraft server would start.

### Mod Version

v3.1.1 or newer

### Minecraft Version

1.20 or newer

### Java Version

Java 17

### Fabric Version

- **Fabric:** 0.14.21-1.20.1
- **Fabric API:** 0.83.1+1.20.1

### Relevant log output

```shell
[08:07:06] [Server thread/ERROR]: Error loading saved data: fw_waystones
java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -1 is negative
	at java.lang.System.arraycopy(Native Method) ~[?:?]
	at java.io.PushbackInputStream.unread(PushbackInputStream.java:232) ~[?:?]
	at net.minecraft.class_26.method_17921(class_26.java:114) ~[server-intermediary.jar:?]
	at net.minecraft.class_26.method_17923(class_26.java:90) ~[server-intermediary.jar:?]
	at net.minecraft.class_26.method_120(class_26.java:70) ~[server-intermediary.jar:?]
	at net.minecraft.class_26.method_20786(class_26.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.class_26.method_17924(class_26.java:42) ~[server-intermediary.jar:?]
	at wraith.fwaystones.util.WaystoneStorage.<init>(WaystoneStorage.java:55) ~[wraith-waystones-3.1.3+mc1.20.jar:?]
	at wraith.fwaystones.util.WaystonesEventManager.lambda$registerEvents$0(WaystonesEventManager.java:22) ~[wraith-waystones-3.1.3+mc1.20.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-31b8918d41d1bef4.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bke000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:4842) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08:07:06] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -1 is negative
	at java.lang.System.arraycopy(Native Method) ~[?:?]
	at java.io.PushbackInputStream.unread(PushbackInputStream.java:232) ~[?:?]
	at net.minecraft.class_26.method_17921(class_26.java:114) ~[server-intermediary.jar:?]
	at net.minecraft.class_26.method_17923(class_26.java:90) ~[server-intermediary.jar:?]
	at wraith.fwaystones.util.WaystoneStorage.loadOrSaveWaystones(WaystoneStorage.java:159) ~[wraith-waystones-3.1.3+mc1.20.jar:?]
	at wraith.fwaystones.util.WaystoneStorage.<init>(WaystoneStorage.java:62) ~[wraith-waystones-3.1.3+mc1.20.jar:?]
	at wraith.fwaystones.util.WaystonesEventManager.lambda$registerEvents$0(WaystonesEventManager.java:22) ~[wraith-waystones-3.1.3+mc1.20.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-31b8918d41d1bef4.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bke000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:4842) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08:07:06] [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/multicraft/servers/server6057/./crash-reports/crash-2023-09-09_08.07.06-server.txt
[08:07:06] [Server thread/INFO]: Stopping server
[08:07:06] [Server thread/INFO]: Saving players
[08:07:06] [Server thread/INFO]: Saving worlds
[08:07:07] [Server thread/INFO]: Saving chunks for level 'ServerLevel[QuestCraft 1.20.1]'/minecraft:overworld
[08:07:10] [Server thread/INFO]: Saving chunks for level 'ServerLevel[QuestCraft 1.20.1]'/minecraft:the_nether
[08:07:10] [Server thread/INFO]: Saving chunks for level 'ServerLevel[QuestCraft 1.20.1]'/minecraft:the_end
[08:07:10] [Server thread/INFO]: ThreadedAnvilChunkStorage (QuestCraft 1.20.1): All chunks are saved
[08:07:10] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[08:07:10] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[08:07:10] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[08:07:10] [Server thread/ERROR]: The Waystone storage is null. This is likely caused by a crash.
```

**Comment by invizbleRope** [comment]
I have located and removed the .dat file for Waystones and the world is running now.
