### ISSUE TITLE
[Bug] Names Keep Resetting [Multiplayer]

### ISSUE THREAD

**Issue by captainharrie** [LordDeatHunter/FabricWaystones#47]
Waystone names keep resetting to the default names.

I believe it's happening after the server restarts because the old names are saved on other people's ends and the new names are just not syncing? But I honestly don't know why it keeps happening, just that they just are not sticking.

**Comment by captainharrie** [comment]
Realised i forgot to say which version my apologies </3 updated the op.

Anyway I'm also running into an issue where I cannot see any of my discovered waystones unless i break the waystone i'm interacting with and place it back down again. This started while I was trying to rename waystones again and accidentally revoked ownership before renaming & immediately crashed minecraft. Problem is I'm not sure if the bugs I'm running into are because of that or because of whatever has been causing the names to reset.

In any case I just had a look in the console and encountered this error:

> 22.07 15:34:14 [Server] Server thread/FATAL Error executing task on Server
> 22.07 15:34:14 [Server] INFO java.lang.NullPointerException: null
> 22.07 15:34:14 [Server] INFO at wraith.waystones.Waystones.lambda$registerPacketHandlers$0(Waystones.java:57) ~[wraith-waystones-2.0.1.jar:?]
> 22.07 15:34:14 [Server] INFO at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
> 22.07 15:34:14 [Server] INFO at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
> 22.07 15:34:14 [Server] INFO at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
> 22.07 15:34:14 [Server] INFO at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
> 22.07 15:34:14 [Server] INFO at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
> 22.07 15:34:14 [Server] INFO at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
> 22.07 15:34:14 [Server] INFO at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
> 22.07 15:34:14 [Server] INFO at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
> 22.07 15:34:14 [Server] INFO at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
> 22.07 15:34:14 [Server] INFO at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
> 22.07 15:34:14 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
> 22.07 15:34:14 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
> 22.07 15:34:14 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
