### ISSUE TITLE
[1.17.1 ] [waystone v2.0.4] Owner cannot open GUI of Waystone

### ISSUE THREAD

**Issue by red2blue** [LordDeatHunter/FabricWaystones#54]
User is trying to use a waystone and i am getting this  error in console

java.lang.NullPointerException: Cannot invoke "java.util.UUID.equals(Object)" because the return value of "wraith.waystones.block.WaystoneBlockEntity.getOwner()" is null
at wraith.waystones.block.WaystoneBlock.method_9534(WaystoneBlock.java:196) ~[wraith-waystones-2.0.4.jar:?]
at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:938) ~[intermediary-server.jar:?]
at net.minecraft.class_3225.redirect$dfj000$activateWithOptionalCactus(class_3225.java:4029) ~[intermediary-server.jar:?]
at net.minecraft.class_3225.method_14262(class_3225.java:327) ~[intermediary-server.jar:?]
at net.minecraft.class_3244.method_12046(class_3244.java:1050) ~[intermediary-server.jar:?]
at net.minecraft.class_2885.method_12547(class_2885.java:30) ~[intermediary-server.jar:?]
at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[intermediary-server.jar:?]
at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
at net.minecraft.class_1255.redirect$glo000$redirectExecuteTask(class_1255.java:521) ~[intermediary-server.jar:?]
at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.handler$dcm000$modifiedRunLoop(MinecraftServer.java:9399) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by LordDeatHunter** [comment]
I have a test build if you want to try it on my discord?
https://discord.gg/vMjzgS4

**Comment by LordDeatHunter** [comment]
Should be fixed.
