### ISSUE TITLE
Crash on startup with version 2.2.0

### ISSUE THREAD

**Issue by CapoFantasma97** [LordDeatHunter/FabricWaystones#69]
The latest version causes the game to crash without any error notification window.

The crash log is here: https://gist.github.com/CapoFantasma97/424c4d004b3698d475a7e83963d71298

```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'waystones'!
Caused by: java.lang.NoSuchMethodError: 'void com.telepathicgrunt.repurposedstructures.world.structures.pieces.StructurePiecesBehavior.addRequiredVillagePiece(java.lang.String, net.minecraft.class_2960, int)'
	at wraith.waystones.compat.RepurposedStructuresCompat.init(RepurposedStructuresCompat.java:35)
	at wraith.waystones.client.WaystonesClient.onInitializeClient(WaystonesClient.java:36)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
```

**Comment by LordDeatHunter** [comment]
Update Repurposed Structures to 2.5.5 or newer:
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric/files/3519661
